include(GNUInstallDirs)

install(TARGETS ${PROJECT_CORE_LIB}
        EXPORT ${PROJECT_CORE_LIB}Targets
        ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        COMPONENT engine
)

install(DIRECTORY "${CMAKE_SOURCE_DIR}/include"
        DESTINATION "${CMAKE_INSTALL_INCLUDE_DIR}/${PROJECT_NAME}"
)